### ISSUE TITLE
Assorted cleanup

### ISSUE THREAD

**Issue by tgerke** [GerkeLab/epiTAD#9]
- [x] Deselect "Hits" for RegulomeDB, it's way messy to have as a default
- [x] Instead of "take me to" for GTEx, ClinVar, and Genome Browser, could the link read as a description of where/why they're going to each of these sites? Something like "GTEx eQTL browser for selected region" etc
- [x] I think the Figure should show by default (i.e. have precedence over the Links tab), since the figure is the most interesting part of the app!
- [x] @gadenbuie are there any R hipster color schemes we should be using in the figure? Sometimes I can't quite get it to look a way I'd like.

**Comment by gadenbuie** [comment]
> R hipster color schemes

I'm a big fan of viridis no matter how many times I see it. Also because it was designed for legibility across media and accesibility for color blind users. I can add them as options.

> Figure should show by default

Would it make sense to move that panel up on the screen? And if so, what would the new  arrangement of panels look like?
